theme = "space-villain"
icons = "material-nf"

[[block]]
block = "focused_window"
max_width = 40

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "used"
unit = "GB"
interval = 20
warning = 70.0
alert = 90.0
format = "{icon} {used}/{total}"

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "used"
unit = "GB"
interval = 20
warning = 150.0
alert = 165.0
format = "{used}/{total}"

[[block]]
block = "backlight"
minimum = 15
maximum = 100
cycle = [100, 50, 0, 50]

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT1"
format = "{percentage}"
full_format = "{percentage}"
hide_missing = true

[[block]]
block = "nvidia_gpu"
label = "RTX 3070"
show_memory = true
show_clocks = true
show_fan_speed = true
interval = 1

[[block]]
block = "time"
interval = 5
format = "%a %m/%d %R"
