#!/bin/bash

helpmsg() {
    echo "Usage: ffnt [OPTION] <keyword>"
    echo "    OPTIONS:"
    echo "    -h    Print this help message and exit."
}

if [ "$1" == "" ]; then
    echo "ffnt: Find Font. Please input a keyword."
    echo "Use ffnt -h to print help message."
    exit 1
elif [ "$1" == "-h" ]; then
    helpmsg
    exit 0
elif [ "$1" == "-f" ]; then
    echo $1 $2
    fc-list | grep -i "$2" | cut -d':' -f1 | sort | uniq
fi

fc-list | grep -i "$1" | cut -d':' -f2 | cut -d',' -f1 | sort | uniq
